name: Continuous Integration
on: push

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Checkout the code in the action runner
      - name: Version check
        run: go version
      - name: Run unit tests
        run: go test ./...
