name: dispatch test

on:
    repository_dispatch:
      types: [ test ]
  
jobs:
  torigger:
    name: commit
    permissions:
      id-token: write # Required for issue-github-token
      contents: write
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
      - uses: actions/checkout@v3 # Checkout the code in the action runner
      - run: ls
      - run: BRANCH=test-dispatch-workflow-auto-commit ./scripts/commit.sh
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}