name: Trigger
on: 
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - '**'
      - '!develop'
  
jobs:
  torigger:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello, World!"

